apiVersion: v2
name: supacontrol
description: A Helm chart for SupaControl - Supabase Management Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - supabase
  - management
  - kubernetes
maintainers:
  - name: QubitQuilt
