apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supacontrol.fullname" . }}-secret
  labels:
    {{- include "supacontrol.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.config.database.password | default (randAlphaNum 32) | b64enc | quote }}
  jwt-secret: {{ .Values.config.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
