apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supacontrol.fullname" . }}-secret
  labels:
    {{- include "supacontrol.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ required "config.database.password is required" .Values.config.database.password | b64enc | quote }}
  jwt-secret: {{ required "config.jwtSecret is required" .Values.config.jwtSecret | b64enc | quote }}
